# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a base Python image
FROM python:3.8-slim

# Set working directory
WORKDIR /app

# Copy requirements file and source code
COPY requirements.txt /app/requirements.txt
COPY src/mssql /app/src/mssql

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the dotenv configuration
COPY .env /app/.env

# Expose any required ports (if applicable, otherwise this can be omitted)
EXPOSE 8000

# Set environment variables for MSSQL connection from .env file
ENV MSSQL_SERVER=${MSSQL_SERVER}
ENV MSSQL_DATABASE=${MSSQL_DATABASE}
ENV MSSQL_USER=${MSSQL_USER}
ENV MSSQL_PASSWORD=${MSSQL_PASSWORD}
ENV MSSQL_DRIVER=${MSSQL_DRIVER}

# Set the entry point to run the server
ENTRYPOINT ["python", "/app/src/mssql/server.py"]
